ktor:
    development: "$DEVELOPMENT_MODE:false"
    application:
        modules:
            - au.com.cding21.ApplicationKt.module
    deployment:
        port: "$PORT:8080"
db:
    type: "$DB_TYPE:postgres"
    mongo:
        user: "$DB_MONGO_USER"
        password: "$DB_MONGO_PASSWORD"
        host: "$DB_MONGO_HOST"
        maxPoolSize: "$DB_MONGO_MAX_POOL_SIZE:20"
        database:
            name: "$DB_MONGO_DATABASE"
    postgres:
        user: "$DB_POSTGRES_USER"
        password: "$DB_POSTGRES_PASSWORD"
        url: "$DB_POSTGRES_URL"
        database:
            name: "$DB_POSTGRES_DATABASE"
jwt:
    issuer: "$JWT_ISSUER"
    domain: "$JWT_DOMAIN"
    audience: "users"
    realm: "Expense Tracker v2"



