ktor:
    development: "$DEVELOPMENT_MODE:false"
    application:
        modules:
            - au.com.cding21.ApplicationKt.module
    deployment:
        port: "$PORT:8080"
    cors:
        staticWebsite: "$CORS_STATIC_WEBSITE:localhost:3000"
        dashboard: "$CORS_DASHBOARD:localhost:3001"
db:
    type: "$DB_TYPE:postgres"
    mongo:
        user: "$DB_MONGO_USER:admin"
        password: "$DB_MONGO_PASSWORD:password"
        host: "$DB_MONGO_HOST:127.0.0.1"
        maxPoolSize: "$DB_MONGO_MAX_POOL_SIZE:20"
        database:
            name: "$DB_MONGO_DATABASE:expense-tracker"
    postgres:
        user: "$DB_POSTGRES_USER:postgres"
        password: "$DB_POSTGRES_PASSWORD:postgres"
        url: "$DB_POSTGRES_URL:jdbc:postgresql://localhost:5432/expense-tracker"
        database:
            name: "$DB_POSTGRES_DATABASE:expense-tracker"
jwt:
    issuer: "$JWT_ISSUER:localhost"
    domain: "$JWT_DOMAIN:localhost"
    audience: "users"
    realm: "Expense Tracker v2"
    secret: "$JWT_SECRET:secret"
    expiresIn: "$JWT_EXPIRATION:3600000"




