name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/frontend/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'src/frontend/.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Generate types
        working-directory: src/backend/
        run: |
          mvn clean install
          mvn typescript-generator:generate@generate-frontend
      - name: Install dependencies
        working-directory: src/frontend/
        run: npm install
      - name: Run tests
        working-directory: src/frontend/
        run: npm test
      - name: Run build
        working-directory: src/frontend/
        run: npm run build

